<?php

namespace App;

use App\EventSubscriber\OrderSubscriber;
use Symfony\Bundle\FrameworkBundle\Kernel\MicroKernelTrait;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\EventDispatcher\EventDispatcher;
use Symfony\Component\HttpKernel\Kernel as BaseKernel;

class Kernel extends BaseKernel
{
    use MicroKernelTrait;

    protected function build(ContainerBuilder $container): void
    {
        parent::build($container); // TODO: Change the autogenerated stub
        $container->register('event_dispatcher', EventDispatcher::class)
            ->setPublic(true);
        $container->register('subscriber_service_id', OrderSubscriber::class)
            ->addTag('kernel.event_subscriber');
    }
}
